FROM jenkins/jenkins:lts-jdk17
USER root
RUN apt update
RUN apt install wget software-properties-common -y
RUN apt install -y python3
RUN apt install -y apt-utils
RUN apt install -y python3-venv
RUN apt install -y openjdk-17-jdk
