pipeline {
    agent any

    stages {
        stage('AAAAAAAAAAAAAAAAAAAAAA') {
            steps {
                sh 'pip3 list'
                echo '---------------------'
                sh 'ls'
                echo "Dependency installation..."
                sh 'pip3 install -r lab2/requirements.txt'
                echo "Dependencies installed."
            }
        }
        stage('Generate train and test dataset') {
            steps {
                echo 'start generate datasets'
                sh 'python3 lab2/src/data_creation.py'
                echo 'finish generate datasets'
            }
        }
        stage('Data preprocessing') {
            steps {
                echo 'start data preprocessing'
                sh 'python3 lab2/src/model_preprocessing.py'
                echo 'finish data preprocessing'
            }
        }
        stage('Create and train model') {
            steps {
                echo 'start create and train model'
                sh 'python3 lab2/src/model_preporation.py'
                echo 'finish create and train model'
            }
        }
        stage('Test model') {
            steps {
                echo 'start testing model'
                sh 'python3 lab2/src/model_testing.py'
                echo 'finish testing model'
            }
        }
    }
    post {
        always {
            echo 'Pipeline has finished.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}