pipeline {
    agent any

    stages {
        stage('Setup environment') {
            steps {
                script {
                    echo 'creating a virtual environment, if not already created'
                    sh '''
                        if [ ! -d ".venv" ]; then
                            env_name=${1:-".venv"}
                            python3 -m venv "$env_name"
                            echo "virtual environment '$env_name' has been created"
                        fi
                    '''

                    echo 'activating virtual environment'
                    sh '''
                        env_name=${1:-".venv"}
                        if [ ! -d "$env_name" ]; then
                            echo "virtual environment '$env_name' not found, use '$0 create [env_name]' to create"
                            return 1
                        fi
                        if [ -z "$VIRTUAL_ENV" ]; then
                            chmod +x ./$env_name/bin/activate
                            ./$env_name/bin/activate
                            echo "virtual environment '$env_name' is activated"
                        else
                            echo "virtual environment has already been activated"
                        fi
                    '''

                    echo 'install dependencies'
                    sh '''
                        ls
                    '''
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline has finished.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}